### ISSUE TITLE
installation details in readme

### ISSUE THREAD

**Issue by andreashlarsen** [BAMresearch/McSAS#18]
Hi, 

this might be trivial, but when installing, I missed some details in the readme: 

1. I had to install imagetk: 
```
sudo apt-get install python3-pil python3-pil.imagetk
```
2. I had to cd to McSAS/src before I could initialize the GUI with: 
```
python -m mcsas
```

I installed on Linux Ubuntu 20.04

**Comment by ibressler** [comment]
Hi Andreas,
Thanks for testing and pointing this out!
Indeed, we moved the python code into an extra `src` folder at some point.
I adjusted the readme accordingly.
Best wishes and happy holidays!
